### ISSUE TITLE
velge and reactjs

### ISSUE THREAD

**Issue by dbhandel** [dscout/velge#13]
Is is possible to use velge within a react component/container? Do you have any suggestions how to accomplish this?
Thanks

**Comment by TaylorBriggs** [comment]
Velge can definitely be used within a React component. The main thing you need is a `ref` to the underlying DOM node ([more about refs](http://facebook.github.io/react/docs/more-about-refs.html)).

For example:
```javascript
import Velge from "velge"
const VelgeComponent = React.createClass({
  render() {
    return React.DOM.div({ className: "velge-container", ref: (ref) => this.container = ref })
  },

  componentDidMount() {
    this.velge = new Velge(this.container)
  },
})
```

`this.container` will be a DOM node -- the same as what you would get from `document.querySelector` or `document.getElementById`.

Let us know if you have any follow-up questions.

**Comment by dbhandel** [comment]
Thanks @TaylorBriggs  for suggesting this code. I am trying to make a freestanding component with Velge that I can then import into a form inside another component. My adaptation of your code (es6-ified) doesn't work:

```
import React, { Component } from 'react';
import Velge from "velge";

class VelgeComponent extends Component {
  componentDidMount() {
    this.velge = new Velge(this.container)
  }
  render() {
    return (
      <div className="velge-container" ref={ (ref) => this.container = ref })> </div> )
  }
})

export default VelgeComponent
```

Any obvious mistakes stand out? 
Thanks again

**Comment by TaylorBriggs** [comment]
Looks like a couple of errant parens. Give this a shot:

```javascript
import React, { Component } from 'react'
import Velge from 'velge'

class VelgeComponent extends Component {
  componentDidMount() {
    new Velge(this.container)
  }

  render() {
    return (
      <div className="velge-container" ref={ (ref) => this.container = ref } />
    )
  }
}

export default VelgeComponent
```

You would only need to keep a reference to the instance (`this.velge`) if you planned on calling its methods in the component or attaching event handlers to it. If you do attach event handlers to the velge instace, you'll want to unbind them in `componentWillUnmount`. You can also pass options into the `Velge` constructor as the second argument.

**Comment by dbhandel** [comment]
Sorry to be taking up so much of your time trying to solve this. I'm very grateful for your help. 

When I tried the ew ncode with the fixed parens, it didn't cause errors but wasn't visible in the browser when rendered inside the component I imported it into. Upon inspected element, I noticed that it's height was 0px. So I added some inline style as shown below. Then it was visible as a red box but wasn't a functioning component. I also tried re-adding the "this.velge = " which I originally had but I think you inadvertently omitted when you retyped my repaired code. Anyway, with the code below, all I  get is a non-functioning red box in the browser. None of the chosen are displayed.

```
import React, { Component } from 'react'
import Velge from 'velge'

class VelgeComponent extends Component {
  componentDidMount() {
    this.velge = new Velge(this.container, {
      choices: [
        { name: 'macintosh' },
        { name: 'cortland' }
      ],
      chosen: [
        { name: 'jonagold' },
        { name: 'snow sweet' }
        ]
      }
    );
  }

  render() {
    return (
      <div style={{backgroundColor: 'red', height: 30}} className="velge-container" ref={ (ref) => this.container = ref } />
    )
  }
}

export default VelgeComponent
```
<img width="1210" alt="screen shot 2016-02-18 at 11 30 32 pm" src="https://cloud.githubusercontent.com/assets/1734740/13166624/c7f5b41a-d697-11e5-8802-4b8bd85c12ac.png">

**Comment by TaylorBriggs** [comment]
Which version of react are you using? You might need to use a string ref instead of the callback, e.g., `ref="container"` on the element attribute and `this.refs.container` when instatiating Velge. Right now, it appears that the ref callback is not happening, so the Velge instance is not being created.

**Comment by dbhandel** [comment]
react version 0.14.7 
I tried your suggestion with above without success. When I log out this.velge inside componentDidMount after it is instantiated I get it in the console: Velge {options: Object, store: Store, ui: UI, addCallbacks: Array[0], remCallbacks: Array[0]} so is was created.

**Comment by TaylorBriggs** [comment]
Sorry you're having so much trouble with this. One thing I notice is your `chosen` values are not included in `choices`. Your options should look like:
```javascript
this.velge = new Velge(this.container, {
  choices: [
    { name: 'macintosh' },
    { name: 'cortland' },
    { name: 'jonagold' },
    { name: 'snow sweet' }
  ],
  chosen: [
    { name: 'jonagold' },
    { name: 'snow sweet' }
  ]
})
```

I also put together a sample app that you should be able to run as-is. I'm not sure what your build step is, but I'm using webpack (and the webpack-dev-server) in this example. 

[react-velge.zip](https://github.com/dscout/velge/files/138261/react-velge.zip)

**Comment by dbhandel** [comment]
Thanks @TaylorBriggs. Got it! This is another good working example to have for others.

**Comment by TaylorBriggs** [comment]
@dbhandel glad it's working now :)

I've opened a [PR](https://github.com/dscout/velge/pull/14) with examples for the popular frameworks so other folks hopefully have an easier time integrating Velge with their projects.
